service: api-world-cup-guesses # NOTE: update this with your service name

frameworkVersion: '3'

plugins:
    - serverless-plugin-typescript
    - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs16.x

package:
  patterns:
    - '!./**'
    - './node_modules/**'
    - './dist/**'

functions:
  backend:
    handler: ./dist/src/lambda.handler
    events: 
      - http:
          method: any
          path: /{any+}