# https://console.aws.amazon.com/iam/home#/users
# serverless deploy --aws-profile tr-apieteg
# serverless deploy --aws-profile tr /prod
# aws configure --profile tr-apieteg

service: api-world-cup

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

useDotenv: true

provider:
  timeout: 30
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: sa-east-1

package:
  individually: true

functions:
  api:
    handler: ./src/handler.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true