service: aws-node # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  backend:
    handler: server.start
    events: 
      - http:
          method: any
          path: /{any+}